package com.phonepe.logger;

import com.phonepe.logger.sink.Sink;

/**
 * Type of the log message {@link #USER_LOG} or
 * {@link #FRAMEWORK_LOG}.
 * {@link #FRAMEWORK_LOG} are used by framework internally to pass various
 * signals such as closure of {@link Sink}. {@link #USER_LOG} indicate log
 * generated by application
 *
 * @author Kaustubh Khasnis
 */
public enum LogType {
    USER_LOG, FRAMEWORK_LOG
}
